name: Build and Deploy

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: dotnet build --configuration Release

      - name: Package
        run: >
          dotnet pack --no-restore --no-build --configuration Release -p:PackageVersion=${{ github.ref_name }} --output .

      - name: List files in the output directory
        run: ls -al

      - name: Publish
        run: >
          dotnet nuget push TestKit.${{ github.ref_name }}.nupkg
          -s https://nuget.pkg.github.com/sifhg/index.json
          -k ${{ secrets.REP_SECRET }}
      - name: Publish to NuGet.org
        run: >
          dotnet nuget push TestKit.${{ github.ref_name }}.nupkg
          -s https://api.nuget.org/v3/index.json
          -k ${{ secrets.NUGET_API_KEY }}
